WITH S AS (SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'Python' OR NAME = 'C#'
)

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE EXISTS (
    SELECT 1 FROM S WHERE (SKILL_CODE & S.CODE) = S.CODE
)
ORDER BY ID;