WITH HEAVY_USER AS (SELECT HOST_ID
                   FROM PLACES
                   GROUP BY HOST_ID
                   HAVING COUNT(*) > 1)

SELECT P.ID, P.NAME, P.HOST_ID
FROM PLACES P JOIN HEAVY_USER H
ON P.HOST_ID = H.HOST_ID
ORDER BY ID;