WITH A AS (SELECT ITEM_ID
          FROM ITEM_INFO
          WHERE RARITY = 'RARE')

SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
JOIN ITEM_TREE T
ON I.ITEM_ID = T.ITEM_ID
WHERE T.PARENT_ITEM_ID IN (SELECT ITEM_ID FROM A)
ORDER BY I.ITEM_ID DESC;