WITH GRADE_SUM AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
)
SELECT G.SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E
JOIN GRADE_SUM G ON E.EMP_NO = G.EMP_NO
WHERE G.SCORE = (SELECT MAX(SCORE) FROM GRADE_SUM)
